
server:
  port: 8090
  
user1 : 
   name : 阿里巴巴
   age : 100
   
spring:
  datasource:
     name: boot
     url: jdbc:mysql://192.168.106.102:3306/boot?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
     username: memeda
     password: 123456789
     driver-class-name: com.mysql.jdbc.Driver